# Generated by Django 5.1.4 on 2025-01-10 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('x_coord', models.FloatField()),
                ('y_coord', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('city1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances_from', to='tsp.city')),
                ('city2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances_to', to='tsp.city')),
            ],
            options={
                'unique_together': {('city1', 'city2')},
            },
        ),
    ]
