# Generated by Django 5.1.4 on 2025-01-11 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Distance',
        ),
    ]
