# Generated by Django 5.1.4 on 2025-01-11 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsp', '0003_alter_city_options_alter_city_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distance',
            options={'ordering': ['city1__name', 'city2__name'], 'verbose_name_plural': 'Distances'},
        ),
    ]
